---
abstract: 'Define Tickit widget structures'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Builder
requires:
  Data::Dump: 0
  Module::Load: 0
  Tickit: 0.12
version: 0.001
